api:
  identifier: Api-Notification
  port: '5001'

logger:
  options:
    level: trace

mongodb:
  url: 'mongodb://127.0.0.1:27017'
  database: 'Api-Notification'
  scheme: mongodb
  hostname: '127.0.0.1'
  port: '27017'
  timeout: '5000'
  options:
    useUnifiedTopology: true
    useNewUrlParser: true
   